# -*- coding: utf-8 -*-
"""0157AL231147

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYPLZFoCryOSwNgEWM9AQWsy7NSKHctV

- Name :pawan tripathi
- Enrollment number : 0157AL231147
- Batch : 5 (MTF) - 2027
- Batch Time : 10:30 AM

- Quiz App with FILE HANDLING
    - 1. registration
    - 2. login (user and admin)
    - 3. quiz
        - 3.1 login
        - 3.2 attempt quiz
            - 3.2.a category (DSA, DBMS, PYTHON)
                display at least 5-10 question randomly(shuffle)
                at a time 1 question with options
        - 3.3 score
            enrollment    category    marks/total marks   datetime
        - 3.4 logout
        - 3.5 update profile, email, branch, year
            contact, name,
        - 3.6 profile
    - 4. exit
"""

from google.colab import files
uploaded = files.upload()

import json
import random
from datetime import datetime

# ---------------- FILE NAMES ----------------
# Yeh files hum use karenge data ko permanently store karne ke liye---
students_file = "students.json"  # student details yahan store honge
scores_file = "scores.json"      # quiz attempt ka record yahan store hoga
questions_file = "questions.json" # quiz questions ke liye file

# ---------------- GLOBAL VARIABLES ----------------
students = {}         # sabhi registered students ka data store karta hai
logged_user = ''      # currently logged-in student ka username
logged = False        # check karta hai user login hai ya nahi


# ---------------- FILE HANDLING FUNCTIONS ----------------
def load_data():
    """File se student data load karega"""
    global students
    try:
        with open(students_file, "r") as f:
            students = json.load(f)
    except FileNotFoundError:
        students = {}


def save_data():
    """Students ka data file me save karega"""
    with open(students_file, "w") as f:
        json.dump(students, f, indent=4)


# ---------------- STUDENT FUNCTIONS ----------------
def register():
    """Naya student register karne ke liye function"""
    global students
    username = input("Enter Username: ")
    if username in students:
        print("Username already exists. Try another one.")
        return

    # user se saari personal details lena
    password = input("Enter Password: ")
    name = input("Enter Full Name: ")
    age = input("Enter Age: ")
    gender = input("Enter Gender: ")
    email = input("Enter Email: ")
    phone = input("Enter Phone Number: ")
    address = input("Enter Address: ")
    dob = input("Enter Date of Birth: ")
    branch = input("Enter Branch: ")
    roll = input("Enter Roll Number: ")

    # dictionary me data store karna
    students[username] = {
        "password": password,
        "name": name,
        "age": age,
        "gender": gender,
        "email": email,
        "phone": phone,
        "address": address,
        "dob": dob,
        "branch": branch,
        "roll": roll
    }
    save_data()  # file me data likhna
    print("Registration Successful ")


def login():
    """Student login karne ke liye function"""
    global logged_user, logged
    username = input("Enter Username: ")
    password = input("Enter Password: ")

    # username aur password verify karna
    if username in students and students[username]["password"] == password:
        logged_user = username
        logged = True
        print("Login Successful ")
    else:
        print("Invalid Username or Password ")


def show_profile():
    """Logged-in student ka profile show karta hai"""
    global logged_user, logged
    if not logged:
        print("You need to login first ⚠️")
        return

    user = students[logged_user]
    print("\n---- Your Profile ----")
    for key, value in user.items():
        if key != "password":
            print(f"{key.capitalize()}: {value}")


def update_profile():
    """Student apni details update kar sakta hai"""
    global logged_user, logged
    if not logged:
        print("You need to login first ⚠️")
        return

    user = students[logged_user]
    print("Which field do you want to update?")
    for key in user.keys():
        if key != "password":
            print(f"- {key}")
    field = input("Enter field name: ").lower()

    # field exist karta hai to update karo
    if field in user and field != "password":
        new_value = input(f"Enter new value for {field}: ")
        user[field] = new_value
        save_data()
        print(f"{field} updated successfully ")
    else:
        print("Invalid field ")


def logout():
    """Logout karne ka function"""
    global logged_user, logged
    if logged:
        logged = False
        logged_user = ''
        print("Logged out successfully ")
    else:
        print("You are not logged in ")


# ---------------- QUIZ MODULE ----------------
def attempt_quiz():
    """Quiz attempt karne ka main function"""
    global logged_user, logged
    if not logged:
        print("Login required to attempt quiz ⚠️")
        return

    # quiz questions file se load karna
    try:
        with open(questions_file, "r") as f:
            questions = json.load(f)
    except FileNotFoundError:
        print("Questions file not found!")
        return

    print("Select Category: DSA / DBMS / PYTHON")
    category = input("Enter category: ").upper()

    if category not in questions:
        print("Invalid category ")
        return

    # randomly 5 questions select karna
    selected_questions = random.sample(questions[category], min(5, len(questions[category])))
    score = 0
    total = len(selected_questions)

    # ek ek question poochhna
    for i, q in enumerate(selected_questions, 1):
        print(f"\nQ{i}: {q['question']}")
        for j, opt in enumerate(q["options"], 1):
            print(f"{j}. {opt}")
        try:
            ans = int(input("Enter your answer (1-4): "))
            if ans == q["answer"]:
                score += 1
        except ValueError:
            print("Invalid input, skipping question.")

    print(f"\n🎯 You scored {score}/{total}")

    # result record karna
    result = {
        "username": logged_user,
        "category": category,
        "marks": score,
        "total": total,
        "datetime": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    # file me store karna
    try:
        with open(scores_file, "r") as f:
            scores = json.load(f)
    except FileNotFoundError:
        scores = []

    scores.append(result)
    with open(scores_file, "w") as f:
        json.dump(scores, f, indent=4)


def show_scores():
    """Student ke saare quiz results show karega"""
    global logged_user, logged
    if not logged:
        print("Please login first ")
        return
    try:
        with open(scores_file, "r") as f:
            scores = json.load(f)
    except FileNotFoundError:
        print("No quiz records found yet.")
        return

    print("\n---- Your Quiz History ----")
    found = False
    for s in scores:
        if s["username"] == logged_user:
            found = True
            print(f"{s['category']} - {s['marks']}/{s['total']} on {s['datetime']}")
    if not found:
        print("No quiz attempts found.")


# ---------------- SYSTEM MANAGEMENT ----------------
def terminate():
    """Program exit karne ka function"""
    print("Exiting System... ")
    exit()


# ---------------- MAIN MENU ----------------
def main():
    """Main function jo menu control karta hai"""
    load_data()
    print("🎓 Welcome to LNCT Quiz System 🎓")
    while True:
        print('''
Choose option:
1. Register
2. Login
3. Show Profile
4. Update Profile
5. Attempt Quiz
6. Show Score
7. Logout
8. Exit
''')
        choice = input("Enter your choice: ")

        if choice == '1':
            register()
        elif choice == '2':
            login()
        elif choice == '3':
            show_profile()
        elif choice == '4':
            update_profile()
        elif choice == '5':
            attempt_quiz()
        elif choice == '6':
            show_scores()
        elif choice == '7':
            logout()
        elif choice == '8':
            terminate()
        else:
            print("Invalid choice, please try again ")


# ---------------- RUN PROGRAM ----------------
if __name__ == "__main__":
    main()